### ISSUE TITLE
Does not work with Raspberry Pi 2

### ISSUE THREAD

**Issue by jokkebk** [WiringPi/WiringPi-Ruby#11]
The library does not work with RaspPi 2. I think the problem is that on the PI 2 the peripheral base address is 0x3F000000 rather than 0x20000000. I found this in ext/wiringpi/WiringPi/wiringPi/wiringPi.c:

#define BCM2708_PERI_BASE                        0x20000000

Unfortunately, my gem knowledge is not enough to test if patching that works, or if something else is needed. The C and Python version of WiringPi already work with Pi2.

http://www.raspberrypi.org/forums/viewtopic.php?f=44&t=100349

**Comment by Gadgetoid** [comment]
This library depends heavily upon WiringPi, which has since been updated to support Pi 2. You could attempt to replace the external files with a fresh clone of WiringPi from here: http://git.drogon.net/?p=wiringPi;a=summary and rebuild.

I plan to do a full update of WiringPi2-Ruby as soon as I have the time, and Pi 2 will be fully supported.

**Comment by Gadgetoid** [comment]
Hopefully this is fixed in https://github.com/WiringPi/WiringPi-Ruby/commit/73e90d8cab45c40bb01d529cf61a9c1633fd1869, but I couldn't get it to build against anything but GCC 4.9 which might be a pain.

**Comment by jdawgaz** [comment]
I Think the #define BCM2708_PERI_BASE 0x20000000 to #define BCM2708_PERI_BASE 0x30000000, is only part of the problem.

The detection of a Pi2 in /proc/cpuinfo is the other part of the problem. Apparently it is not as strait forward as it used to be.

and BTW I did a refresh (and build) of the wiringpi from george and it did not fix this issue.

Jerry

**Comment by jdawgaz** [comment]
typo: should be BCM2708_PERI_BASE 0x3F000000

**Comment by sean2121** [comment]
It still doesn't work. Do we have to using the python?

**Comment by niccolosanarico** [comment]
+1, it is not working for me either.

Thank you,

Nico

**Comment by Gadgetoid** [comment]
This should be fixed by the latest release, which is based upon WiringPi 2.32 and includes support for Pi 2 and Pi 3.

The version number has bumped to `2.32.0`, the first/second most significant numbers to track the WiringPi version, and the last to track revisions to the bindings and supporting Ruby module.
